## This pair of functions will effeciently compute the invers of a matrix. 
## After computing the inverse once, the result will be cached and can be
## retrieved if the inverse is desired again, rather than re-computing it.

## The function makeCacheMatrix serves two purposes. It creates an new
## object based on the original matrix that will store both the matrix
## and the cached inverse. Additionally, it generates four functions
## (get, set, getinv, setinv) used for getting and setting the cached
## inverse.

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setinv <- function(invmat) inv <<- invmat
  getinv <- function() inv
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


## The function cacheSolve is used to determine the matrix of x,
## where x is the object generated by the function makeCachematrix.
## The function checks if there is already a cached value and if
## there is, it retuns the cached inverse. Otherwise, it computes
## and returns the inverse.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  inv <- x$getinv()
  if(!is.null(inv)) {
    message("getting cached data")
    return(inv)
  }
  data <- x$get()
  inv <- solve(data, ...)
  x$setinv(inv)
  inv
  
  }
